<?php
/**
 * Amazon Diagnostics
 *
 * @category    Amazon
 * @package     FLATz_AmazonDiagnostics
 * @copyright   Copyright (c) 2015 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/* @var $this FLATz_AmazonPayments_Block_Adminhtml_Diagnostics */
?>

<textarea id="flatz_amazon_diagnostics_result" cols="40" style="width:100%; font-family:monospace;" wrap="off" readonly="readonly"></textarea>
