<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     FLATz_AmazonPayments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<?php
    $_helper = Mage::helper('flatz_amazon_payments/data');

    $base = ($_helper->isAmazonSandbox()) ? 
            'https://origin-na.ssl-images-amazon.com/images/G/09/EP/offAmazonPayments/sandbox/prod/lpa/js/Widgets.js' : 'https://static-fe.payments-amazon.com/OffAmazonPayments/jp/lpa/js/Widgets.js';
    $jsAmazon = $base . '?sellerId=' . $_helper->getSellerId();

    $isPopup = Mage::helper('flatz_amazon_login/data')->isPopup();
?>

<script type='text/javascript'>
    window.onAmazonLoginReady = function() {
        amazon.Login.setClientId('<?php echo $_helper->getClientId(); ?>');

        <?php if (!$isPopup) : ?>
        amazon.Login.setUseCookie(true);
        <?php endif; ?>

    };

    <?php if (!$isPopup) : ?>
    src = '<?php echo $jsAmazon; ?>';
    <?php endif; ?>

</script>

<script type='text/javascript' src='<?php echo $jsAmazon; ?>'></script>


<?php if ($_helper->showModal()) : ?>

<script type="text/javascript">

AmazonModal = Class.create();

AmazonModal.prototype.initialize = function(width) {
    this.width = width;
}

AmazonModal.prototype.show = function(url) {

    this.oPopup = new Window({
        id:'amazon_modal',
        className: 'alphacube',
        url: url,
        width: this.width,
        height: 700,
        minimizable: false,
        maximizable: false,
        showEffectOptions: {
            duration: 0.4
        },
        hideEffectOptions:{
            duration: 0.4
        },
        destroyOnClose: true,
        onShow: function() { Event.observe($('overlay_modal'), 'click', function() { Windows.closeAll(); }) },
        onClose: function() { $('overlay_modal').remove(); }
    });
    this.oPopup.setZIndex(100);
    this.oPopup.showCenter(true);

    // Reponsive modal
    Event.observe(window, "resize", this.resize.bind(this));
    this.resize();
}

AmazonModal.prototype.resize = function() {
    var oSize = this.oPopup.getSize();
    var width = document.viewport.getWidth();

    if (this.width > width) {
      this.oPopup.setSize(width, oSize.height);
      this.oPopup.showCenter(true);
    }
}




document.observe("dom:loaded", function() {
    var amazonModal = new AmazonModal(1020);
    amazonModal.show('<?php print $_helper->getStandaloneUrl(); ?>?ajax=1&<?php print htmlentities($_SERVER['QUERY_STRING']); ?>');
});


</script>

<?php endif; ?>